sudo: true
dist: trusty

language: perl

install:
  - ./.travis/install-dependencies.sh

script:
  - ./functional_tests/testperl5_4-test.sh -p $TRAVIS_BUILD_DIR/testperl5_4.pl -d functional_tests/test_data
  - ./.travis/unit-test.sh
